query {
  categories(treeLevel: 4) @context(provider: "vtex.store-graphql") {
    id
    name
    href
    slug
    hasChildren
    children {
      id
      name
      href
      slug
      hasChildren
      children {
        id
        name
        href
        slug
      }
    }
  }
}